In [19]:
# Load packages

import pandas as pd
import numpy as np
import os

In [20]:
# Read CSV
df_2018 = pd.read_csv('../data_2018/18incd.csv')

df_2022 = pd.read_csv('../data_2023/22incdoh.csv')


df_2018.head(20)

,"OHIO, INDIANA, MICHIGAN, MISSOURI, PENNSYLVIANIA, WISCONSIN",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Individual Income Tax Returns: \nSelected Inco...,Individual Income Tax Returns: \nSelected Inco...,NaN,NaN,NaN
1,[Money amounts are in thousands of dollars],[Money amounts are in thousands of dollars],NaN,NaN,NaN
2,State,Congressional\ndistrict [1],Size of adjusted gross income by congressional...,Number of returns,Percentage
3,NaN,NaN,NaN,NaN,NaN
4,Ohio,1,NaN,"358,550",100
5,Ohio,1,Under $1,"2,940",0.819969321
6,Ohio,1,"$1 under $10,000","47,370",13.21154651
7,Ohio,1,"$10,000 under $25,000","69,320",19.3334263
8,Ohio,1,"$25,000 under $50,000","84,850",23.66476084
9,Ohio,1,"$50,000 under $75,000","50,290",14.02593781
10,Ohio,1,"$75,000 under $100,000","32,900",9.175847162
11,Ohio,1,"$100,000 under $200,000","50,500",14.08450704
12,Ohio,1,"$200,000 under $500,000","16,260",4.534932366
13,Ohio,1,"$500,000 or more","4,120",1.149072654
14,NaN,NaN,NaN,NaN,NaN
15,Ohio,2,NaN,"345,020",100
16,Ohio,2,Under $1,"3,270",0.947771144
17,Ohio,2,"$1 under $10,000","42,180",12.22537824
18,Ohio,2,"$10,000 under $25,000","64,520",18.7003652
19,Ohio,2,"$25,000 under $50,000","86,370",25.0333314

In [22]:
import pandas as pd

def clean_dataframe(df, separator=" "):
    """
    Cleans a pandas DataFrame by:
    1. Deleting the first 3 rows
    2. Dropping empty rows
    3. Combining the first two columns into one
    4. Renaming all columns
    
    Parameters:
        df (pd.DataFrame): Input DataFrame
        new_column_names (list): Optional list of new column names
        separator (str): String separator to combine first two columns (default = space)
    
    Returns:
        pd.DataFrame: Cleaned DataFrame
    """
    
    # 1. Drop first 3 rows
    df = df.iloc[3:].copy()
    
    # 2. Drop completely empty rows
    df = df.dropna(how="all")
    
    # 3. Combine first two columns into one
    state_col, district_col = df.columns[:2]
    df["CD116"] = (
            df[state_col].astype(str).str.strip()
            + " "
            + df[district_col].astype(int).astype(str).str.zfill(2)
        )
    cols = ["CD116"] + [c for c in df.columns if c != "CD116"]
    df = df[cols]
    df = df.drop(columns=[state_col, district_col, "Unnamed: 3"])

    # Rename columns
    new_column_names=["CD116", "Household Income", "Percentage"]
    df.columns = new_column_names
    df = df.dropna(subset=["Household Income"])

    # Change to wide format
    df_wide = df.pivot(index="CD116", columns="Household Income", values="Percentage").copy()
    df_wide = df_wide.reset_index()

    
    return df_wide

df_2018_clean = clean_dataframe(df_2018)

df_2022_clean = clean_dataframe(df_2022)
df_2022_clean = df_2022_clean.rename(columns={'CD116': 'CD119'})
df_2022_clean.head(20)

Household Income,CD119,"$1 under $10,000","$10,000 under $25,000","$100,000 under $200,000","$200,000 under $500,000","$25,000 under $50,000","$50,000 under $75,000","$500,000 or more","$75,000 under $100,000",Under $1
0,Ohio 01,10.42109037,16.41342415,16.46306152,6.364614069,23.02898271,15.03185065,1.5635772,9.574497422,1.138901911
1,Ohio 02,9.695713504,15.36402107,15.91386706,5.85542793,24.16731439,16.18447189,1.462417595,10.18222644,1.174540116
2,Ohio 03,10.38239692,21.03183081,9.885708182,2.197714164,29.83870968,16.66577654,0.440610981,8.50245674,1.054795984
3,Ohio 04,10.41397913,16.38911692,14.28403894,2.770611,26.37797584,17.81400258,0.501348657,10.33775067,1.111176264
4,Ohio 05,10.00449135,15.00112284,16.66573097,4.095553559,24.43858073,17.06433865,0.892656636,10.85223445,0.985290815
5,Ohio 06,10.53063907,17.98258584,13.87875801,2.720551996,26.12781337,16.54345326,0.614424183,10.36635453,1.235419747
6,Ohio 07,10.3349883,16.29287223,14.92609713,3.398390687,25.28676596,17.38857502,0.61633282,10.65171489,1.104262969
7,Ohio 08,10.12483063,15.98293309,16.25392798,4.116816098,25.04973045,16.48167902,0.683253092,10.2747427,1.032086949
8,Ohio 09,10.98064861,20.60283583,10.69528254,2.609910526,28.31069231,16.38476859,0.543979073,8.709610297,1.162272227
9,Ohio 10,10.23387586,17.38313434,15.32768639,3.9403313,25.22043306,16.09089069,0.699603943,10.00549276,1.098551646
10,Ohio 11,11.82329159,23.22584886,9.584853565,3.816191697,27.38717418,14.24251389,1.245768004,7.136048384,1.538309831
11,Ohio 12,9.735143104,13.11321234,20.12607392,8.507447512,20.22774643,14.80097606,1.807228916,10.64257028,1.039601444
12,Ohio 13,10.83472853,20.06397991,10.91246113,2.006099019,28.79394882,16.85302559,0.352786415,9.046878737,1.136091844
13,Ohio 14,10.38079914,13.53982301,18.27299544,6.446768571,21.1638509,16.30195763,1.665325825,10.99758648,1.230893001
14,Ohio 15,9.344475497,14.30310745,17.77857716,5.265779352,23.0056172,16.90694264,1.026591771,11.22333213,1.145576801
15,Ohio 16,10.01055966,13.64044351,18.48204857,5.385427666,21.72914467,17.1092925,1.103484688,11.47307286,1.066525871

In [23]:
df_2018_clean.to_csv('../data_2018/demographic_data/18incd_clean.csv')

df_2022_clean.to_csv('../data_2023/22incdoh_clean.csv')